context:
  version: "1.3.5"

package:
  name: flagembedding
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/FlagEmbedding/FlagEmbedding-${{ version }}.tar.gz
    sha256: a0714cb8dd03f38e74b84530684c47ad8e0442ab1f4cbb7b0bcd4017dafb9f9c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=1.6.0
    - transformers >=4.44.2
    - datasets >=2.19.0
    - accelerate >=0.20.1
    - sentence-transformers
    - peft
    - sentencepiece
    - protobuf

tests:
  - python:
      imports:
        - FlagEmbedding
      pip_check: false
      python_version: ${{ python_min }}

about:
  homepage: https://github.com/FlagOpen/FlagEmbedding
  summary: FlagEmbedding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
